development:
  adapter: postgresql
  encoding: utf8
  database: mysite_development
  pool: 5
  username: corydiamand
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mysite_test
  pool: 5
  username: corydiamand
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mysite_production
  pool: 5
  username: 
  password: